name: Lint check
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  Lint_Job:
    name: Lint_Name_test
    runs-on: ubuntu-22.04
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Message
        run: echo "Lint Message"
  Build_Job_111:
    name: Build_Job_111
    runs-on: ubuntu-22.04
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Message
        run: echo "Lint Message"
  Lint_Job_test:
    name: Lint_Name_Test
    runs-on: ubuntu-22.04
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Message
        run: echo "Lint Message"
