name: Lint check
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  Lint_Job:
    name: Lint_Name
    runs-on: ubuntu-22.04
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Message
        run: echo "Lint Message"
  Lint_Job1:
    name: Lint_Name1
    runs-on: ubuntu-22.04
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Message
        run: echo "Lint Message"
