name: Parameter Workflow Java Eg
on:
  workflow_dispatch:
env:
  java_version: "17"
jobs:
  Build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: setting java version
        run: echo "setting up java version $java_version"
      - name: building java test
        run: echo "building java test"
  
  Deployment:
    name: Depl
    runs-on: ubuntu-22.04
    env:
      appl: "Ashish"
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: building docker application
        run: echo "building docker application $appl-app"
          
