name: Hello world pipeline
on:
  workflow_dispatch:
jobs:
  Build:
    name: print hello
    runs-on: ubuntu-22.04
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: create file
        run: |
          echo "hello" >> file.txt
          ls -lhrt
